rwx-research/homebrew-tap

.github/workflows/ci.yml
=> test the tap

.github/workflows/ci.yml, Formula/abq.rb, Formula/abq@1.rb
=> pull in newer abq

.github/workflows/ci.yml, Formula/abq.rb, Formula/abq@1.rb
will be short lived because we're about to release 1.1.0 but still
=> bump to 1.1.0

.github/workflows/ci.yml, Formula/abq.rb, Formula/abq@1.rb
=> bump to 1.1.2

Formula/captain.rb, Formula/captain@1.rb
For those who update this in the future:
```sh
$ curl {release_url} -o captain
$ sha256sum captain
```
=> Add homebrew taps for Captain

Formula/captain.rb, Formula/captain@1.rb
Updating this to the latest version
=> Update Captain to 1.5.4

.github/workflows/ci.yml, Formula/captain.rb, Formula/captain@1.rb
=> Update captain to ~1.9.3~ 1.9.4

README.md, bin/update-captain-formulae
Following https://github.com/rwx-research/homebrew-tap/pull/26#discussion_r1164380625
=> Improve the script to update the version of captain

.github/workflows/abq-ci.yml, Formula/abq.rb, Formula/abq@1.rb
=> upgrade abq to 1.5.0

.github/workflows/abq-ci.yml, Formula/abq.rb, Formula/abq@1.rb
=> update abq to v1.6.0

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb
following captain release yesterday
=> update captain to v1.11.2

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb
See [Captain release notes](https://github.com/rwx-research/captain/releases/tag/v1.11.6).
=> Update Captain to v1.11.6

.github/workflows/mint-ci.yml, Formula/mint.rb, README.md, bin/update-mint-formulae
=> Add Formulae for Mint

.github/workflows/mint-ci.yml, Formula/mint.rb
Shaken not stirred.
https://github.com/rwx-research/mint-cli/releases/tag/v0.0.7
https://github.com/rwx-research/mint-cli/releases/tag/v0.0.6
=> Release Mint v0.0.7

.github/workflows/mint-ci.yml, Formula/mint.rb
=> Update mint to 0.0.9

.github/workflows/mint-ci.yml, Formula/mint.rb
https://github.com/rwx-research/mint-cli/releases/tag/v0.1.0
=> Update mint to 0.1.0

.github/workflows/mint-ci.yml, Formula/mint.rb
See https://github.com/rwx-research/mint-cli/releases/tag/v0.2.0
=> Bump Mint to v0.2.0

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb, bin/update-abq-formulae, bin/update-captain-formulae, bin/update-mint-formulae
- **Use /usr/bin/sed since gnu-sed does not like @ in filepaths**
- **Update captain to 1.12.0**
=> Updates Captain to 1.12.0

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb
https://github.com/rwx-research/captain/releases/tag/v1.13.1
=> Release Captain 1.13.1

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb
https://github.com/rwx-research/captain/releases/tag/v1.13.2
https://github.com/rwx-research/captain/releases/tag/v1.13.3
=> Release Captain 1.13.3

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb
https://github.com/rwx-research/captain/releases/tag/v1.14.1
=> Release Captain 1.14.1

.github/workflows/mint-ci.yml, Formula/mint.rb
https://github.com/rwx-research/mint-cli/releases/tag/v1.3.1
=> Release Mint 1.3.1

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb
https://github.com/rwx-research/captain/releases/tag/v1.15.0
=> Release Captain 1.15.0

.github/workflows/abq-ci.yml, .github/workflows/captain-ci.yml, .github/workflows/mint-ci.yml, Formula/captain.rb, Formula/captain@1.rb
https://github.com/rwx-research/captain/releases/tag/v1.17.1
=> Release Captain 1.17.1

.github/workflows/mint-ci.yml, Formula/mint.rb
https://github.com/rwx-research/mint-cli/releases/tag/v1.5.0
=> Release Mint 1.5.0

.github/workflows/mint-ci.yml, Formula/mint.rb
https://github.com/rwx-research/mint-cli/releases/tag/v1.5.1
=> Release Mint 1.5.1

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb
https://github.com/rwx-research/captain/pull/123
=> Release Captain 1.19.3

.github/workflows/captain-ci.yml, Formula/captain.rb, Formula/captain@1.rb
https://github.com/rwx-research/captain/releases/tag/v2.2.1
=> Release Captain 2.2.1
